# Generated by Django 4.1.1 on 2023-02-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthDate', models.DateTimeField(verbose_name='date of birth')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('accessLevel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=49)),
                ('phone', models.IntegerField()),
                ('needHelp', models.BooleanField()),
                ('ethicsViolation', models.TextField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vim', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('isPurchased', models.BooleanField()),
                ('isPending', models.BooleanField()),
                ('reservedDays', models.JSONField()),
                ('vehicleType', models.CharField(max_length=20)),
                ('isInsured', models.BooleanField()),
                ('isLoadJacked', models.BooleanField()),
                ('dateCheckedOut', models.DateTimeField()),
                ('dateCheckedIn', models.DateTimeField()),
                ('image', models.TextField()),
            ],
        ),
    ]
