# Generated by Django 4.1.7 on 2023-03-07 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('permission', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('employee', 'employee')], default='user', max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('needHelp', models.BooleanField(default=False)),
                ('ethicsViolation', models.TextField(blank=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=200)),
                ('isPurchased', models.BooleanField()),
                ('isPending', models.BooleanField()),
                ('reservedDays', models.JSONField(null=True)),
                ('vehicleType', models.CharField(max_length=20)),
                ('isInsured', models.BooleanField()),
                ('isLoadJacked', models.BooleanField()),
                ('dateCheckedOut', models.DateTimeField(null=True)),
                ('dateCheckedIn', models.DateTimeField(null=True)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('amountDue', models.FloatField()),
                ('autoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshop.autouser')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshop.vehicle')),
            ],
        ),
    ]
