# Generated by Django 4.1.1 on 2023-02-27 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('permission', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('needHelp', models.BooleanField()),
                ('ethicsViolation', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vim', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('isPurchased', models.BooleanField()),
                ('isPending', models.BooleanField()),
                ('reservedDays', models.JSONField(null=True)),
                ('vehicleType', models.CharField(max_length=20)),
                ('isInsured', models.BooleanField()),
                ('isLoadJacked', models.BooleanField()),
                ('dateCheckedOut', models.DateTimeField(null=True)),
                ('dateCheckedIn', models.DateTimeField(null=True)),
                ('image', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autoshop.user')),
            ],
        ),
    ]
