# Generated by Django 4.1.7 on 2023-03-08 00:30

from django.db import migrations

from django.db import migrations

def populate_db(apps, schema_editor):
    Vehicle = apps.get_model('autoshop', 'Vehicle')
    # default vehicles
    Vehicle.objects.create(name="Old Batmobile", vin="ZAMGJ45A390047326", vehicleType="", imageURL="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qPl0klIzw6f7Q142ZHjoKAHaEK%26pid%3DApi&f=1&ipt=8d006f8577bac6366ce5b74c63dc486b9d2b2c75431eb777ea868719e497618a&ipo=images")
    Vehicle.objects.create(name="Super Jet", vin="KMHD25LE1DU042025", vehicleType="",  imageURL="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.rbbx-bgnjCnxpQ0FWS7SigHaE8%26pid%3DApi&f=1&ipt=5c3faad3bc258976d49340d789ed6cbf45ef61f4f158a4b268cb0e6b034bbed9&ipo=images")
    Vehicle.objects.create(name="Batcycle", vin="JH4CC2650NC000393", vehicleType="", pricePerDay=2000, imageURL="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.MZYgmPyleX4SQ-S-b34vKwHaEK%26pid%3DApi&f=1&ipt=0c0daaf3d576d0c67c91b6dc596890da62eda8f20a8909a19296c7ce515319cf&ipo=images")
    Vehicle.objects.create(name="Superman Cape", vin="WDDDJ72X97A116339", vehicleType="", pricePerDay=15000, imageURL="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.602l4GojlP4-mftq7Mw5HgHaDt%26pid%3DApi&f=1&ipt=d5b9661c726be1ff983125577aa316bddb0d37cc90c4bb8a7eafadd879653666&ipo=images")
    Vehicle.objects.create(name="Red Camaro", vin="camaro", vehicleType="", pricePerDay=1200, imageURL="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.LdV8aI-mOHtEO8tGRTpAtAHaEK%26pid%3DApi&f=1&ipt=816e07fe44d1ebbf26ae5bbcf0d3ad20fff8fafd8e6a17ef2f566c5eaff3b3d1&ipo=images")
    Vehicle.objects.create(name="Black Camaro", vin="camaro", vehicleType="", imageURL=
    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Z9pqTfEuNXJF_-A5hCBgbgHaEr%26pid%3DApi&f=1&ipt=3c490744798d67b20ff3d46544c92edaec063a00fa68151797b7fa79ca8d6c6e&ipo=images")
    Vehicle.objects.create(name="Silver Camaro", vin="camaro", vehicleType="", imageURL=
    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.hpx3ydjbEb9RVILHNlpsyAHaEo%26pid%3DApi&f=1&ipt=f85259e9cf5c1069036f538d26ddf7777287c2ec1c048206094ecbff16bc14b0&ipo=images")

class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0001_initial'),
    ]

    operations = [migrations.RunPython(populate_db), ]