# Generated by Django 3.2.8 on 2023-02-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethicsViolation',
            field=models.TextField(blank=True),
        ),
    ]
