# Generated by Django 4.1.7 on 2023-03-07 19:43

from django.db import migrations
from uuid import uuid4
from datetime import datetime, timedelta
import random
from django.contrib.auth import get_user_model

def populate_db(apps, schema_editor):
    User = get_user_model()

    for _ in range(10):
        authUser = User.objects.create_user(username=f"{uuid4()}@gmail.com", password="abc")



class Migration(migrations.Migration):
    dependencies = [
        ('autoshop', '0001_initial'),
    ]

    operations = [migrations.RunPython(populate_db),
                  ]