# Generated by Django 4.1.7 on 2023-03-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autouser',
            name='ethicsViolation',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='autouser',
            name='location',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amountDue',
            field=models.FloatField(default=100),
        ),
    ]
