# Generated by Django 4.1.7 on 2023-03-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0002_alter_autouser_ethicsviolation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='dateCheckedIn',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='dateCheckedOut',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='reservedDays',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='isInsured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='isLoadJacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='isPending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='isPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
