# Generated by Django 3.2.8 on 2023-02-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0002_alter_user_ethicsviolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vim',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default=13123124123123123, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(max_length=50),
        ),
    ]
