# Generated by Django 4.1.7 on 2023-03-07 20:52



# python manage.py makemigrations --empty autoshop --name populate
# python manage.py makemigrations $ python manage.py migrate

from django.db import migrations
from uuid import uuid4


def populate_db(apps, schema_editor):
    # TODO: Update this to include better vehicle URLs and descriptions
    Vehicle = apps.get_model('autoshop', 'Vehicle')

    for i in range(30):
        vehicle = Vehicle(name=f"Vehicle {i}", location="1234 Main St", image="https://www.google.com",
                          vin=str(uuid4()))
        vehicle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0002_populate'),
    ]

    operations = [migrations.RunPython(populate_db),
    ]
