# Generated by Django 4.1.7 on 2023-03-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0003_rename_hoursworked_autouser_hoursowed_autouser_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autouser',
            name='hoursOwed',
            field=models.FloatField(default=0),
        ),
    ]
