# Generated by Django 4.1.7 on 2023-03-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0003_remove_vehicle_datecheckedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startDate',
            field=models.DateField(),
        ),
    ]
