# Generated by Django 3.2.8 on 2023-02-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0003_auto_20230227_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reservedDays',
            field=models.JSONField(blank=True),
        ),
    ]
