# Generated by Django 4.1.7 on 2023-03-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0004_alter_autouser_hoursowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='isInsured',
        ),
        migrations.AddField(
            model_name='reservation',
            name='isInsured',
            field=models.BooleanField(default=False),
        ),
    ]
