# Generated by Django 4.1.7 on 2023-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0004_alter_reservation_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default='Logan', max_length=200),
        ),
    ]
