# Generated by Django 3.2.8 on 2023-02-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0004_alter_vehicle_reserveddays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='reservedDays',
        ),
    ]
