# Generated by Django 3.2.8 on 2023-02-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0005_remove_vehicle_reserveddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='reservedDays',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(max_length=20),
        ),
    ]
