# Generated by Django 4.1.7 on 2023-03-07 18:42

from django.db import migrations
from uuid import uuid4
from datetime import datetime, timedelta
import random

def populate_db(apps, schema_editor):
    AutoUser = apps.get_model('autoshop', 'AutoUser')
    Vehicle = apps.get_model('autoshop', 'Vehicle')
    Reservation = apps.get_model('autoshop', 'Reservation')
    # Create some users
    for i in range(10):
        user = AutoUser(name=f"User {i}", permission="user", balance=100,  location="1234 Main St", email=f"{uuid4()}@gmail.com")
        user.save()
        vehicle = Vehicle(name=f"Vehicle {i}", location="1234 Main St", image="https://www.google.com", vin=str(uuid4()))
        vehicle.save()
        for i in range(10):
            if random.randint(0, 10) % 2 == 0:
                startDate = datetime.today() + timedelta(days=i)
            else:
                startDate = datetime.today() - timedelta(days=i)
            endDate = startDate + timedelta(days=random.randint(0, 5))
            reservation = Reservation(autoUser=user, vehicle=vehicle, startDate=startDate, endDate=endDate)
            reservation.save()
        vehicle = Vehicle(name=f"Free Vehicle {i}", location="1234 Main St", image="https://www.google.com", vin=str(uuid4()), vehicleType="Chevrolet", isPurchased=True)
        vehicle.save()
    
    # Create Admin
    user = AutoUser(name=f"Admin", permission="admin", balance=1000,  location="1234 Main St", email=f"{uuid4()}@gmail.com")
    user.save()

    # Create Employee
    user = AutoUser(name=f"Employee", permission="employee", balance=1000, email=f"{uuid4()}@gmail.com")
    user.save()
    user = AutoUser(name=f"Employee", permission="employee", balance=500, email=f"{uuid4()}@gmail.com")
    user.save()

    # Create basic user
    user = AutoUser(name=f"User {i}", permission="user", email=f"abc")
    user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0005_alter_vehicle_image_alter_vehicle_location'),
    ]

    operations = [migrations.RunPython(populate_db),
    ]
