# Generated by Django 4.1.7 on 2023-03-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0006_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='autouser',
            name='hoursWorked',
            field=models.IntegerField(default=0),
        ),
    ]
