from .endpointTests.authenticationEndpointTests import TestAuthentication
from .endpointTests.userEndpointTests import TestUserEndpoints
from .endpointTests.vehicleEndpointTests import TestVehicleEndpoints
# from .endpointTests.ReservationTests import TestReservationEndpoints

